packages:
  - "packages/*"

# Define a catalog of version ranges.
catalogs:
  default:
    "@types/vscode": 1.107.0
    "@types/node": 22.18.0
    "@types/mocha": 10.0.10
    "glob": 13.0.0
    "@types/glob": 9.0.0
