packages:
  - packages/*

catalogs:
  default:
    "@superoffice/webapi": 11.7.727
    langium: ~4.4.0
    langium-cli: ~4.4.0
    vite: npm:@voidzero-dev/vite-plus-core@0.1.21
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.21
    vite-plus: 0.1.21
    vscode-languageserver: 10.1.1
    vscode-languageclient: 10.1.1
    "@types/node": 22.18.0
    "@types/mocha": 10.0.10
    "@types/vscode": 1.107.0
    typescript: 5.8.3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
