packages:
  - packages/*

catalogs:
  default:
    "@superoffice/webapi": 11.7.727
    "@types/glob": 9.0.0
    "@types/mocha": 10.0.10
    "@types/node": 22.18.0
    "@types/vscode": 1.107.0
    "@vitest/coverage-v8": 4.0.18,
    esbuild: 0.25.0
    glob: 13.0.0
    vitest: 4.0.18
    vscode-languageserver: 9.0.1

overrides:
  crmscript-language: link:packages/language
