name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts/*"
          cache: true

      - run: vp install
      - run: vp run langium:generate
      - run: vp check
      - run: vp test
